export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/0.jpeg",
    username: "Isaac Ansah",
  },

  {
    id: 2,
    profilePicture: "assets/person/1.jpeg",
    username: "Isaac Kwame Amoah",
  },

  {
    id: 3,
    profilePicture: "assets/person/2.jpeg",
    username: "Naan Kofi Ansah",
  },

  {
    id: 4,
    profilePicture: "assets/person/3.jpeg",
    username: "Isaac Sarfo kwame",
  },
  {
    id: 5,
    profilePicture: "assets/person/4.jpeg",
    username: "Isheamel Ansah",
  },
  {
    id: 6,
    profilePicture: "assets/person/5.jpg",
    username: "Anita Ansah",
  },
  {
    id: 7,
    profilePicture: "assets/person/6.jpeg",
    username: "Emmanuel Kwadjo Ansah",
  },
  {
    id: 8,
    profilePicture: "assets/person/7.jpg",
    username: "sarfo Khalid",
  },
  {
    id: 9,
    profilePicture: "assets/person/8.jpeg",
    username: "Rejoice Ansah",
  },
  {
    id: 10,
    profilePicture: "assets/person/9.jpeg",
    username: "Richard Boakye",
  },
  {
    id: 11,
    profilePicture: "assets/person/10.jpg",
    username: "Prempeh Emma",
  },
  {
    id: 12,
    profilePicture: "assets/person/11.jpeg",
    username: "Vasco Obeng",
  },
  {
    id: 13,
    profilePicture: "assets/person/12.jpg",
    username: "Boakye Emmanuel",
  },
  {
    id: 14,
    profilePicture: "assets/person/13.jpeg",
    username: "Adjei Ayim",
  },
  {
    id: 15,
    profilePicture: "assets/person/14.jpeg",
    username: "Agamah Richard",
  },
  {
    id: 16,
    profilePicture: "assets/person/15.jpeg",
    username: "Kumfo Boamah",
  },
  {
    id: 17,
    profilePicture: "assets/person/16.jpeg",
    username: "Nimo Daniel",
  },
  {
    id: 18,
    profilePicture: "assets/person/17.jpeg",
    username: "Asiamah Asara",
  },
];
export const Posts = [
  {
    id: 1,
    desc: "Love for All, Hatred for none.",
    photo: "assets/posts/0.jpg",
    date: "10 mins ago",
    userId: 1,
    like: 34,
    comment: 89,
  },
  {
    id: 2,
    desc: "alwways reason up fast",
    photo: "assets/posts/1.jpg",
    date: "40 mins ago",
    userId: 2,
    like: 344,
    comment: 849,
  },
  {
    id: 3,
    desc: "What is the actual reason for the love?",
    photo: "assets/posts/2.jpeg",
    date: "50 mins ago",
    userId: 3,
    like: 374,
    comment: 899,
  },
  {
    id: 4,
    desc: "Have you eaten for the entire season",
    photo: "assets/posts/3.jpg",
    date: "15 mins ago",
    userId: 4,
    like: 343,
    comment: 896,
  },
  {
    id: 5,
    desc: "Love for All, Hatred for none, that is the motto of islam.",
    photo: "assets/posts/4.jpeg",
    date: "10 mins ago",
    userId: 5,
    like: 374,
    comment: 819,
  },
  {
    id: 6,
    desc: "The man has done it again",
    photo: "assets/posts/5.jpeg",
    date: "15 hrs ago",
    userId: 6,
    like: 3754,
    comment: 8129,
  },
  {
    id: 7,
    desc: "Do you want to be loved?",
    photo: "assets/posts/6.jpeg",
    date: "30 mins ago",
    userId: 7,
    like: 3724,
    comment: 19,
  },
  {
    id: 8,
    desc: "? will you",
    photo: "assets/posts/7.jpg",
    date: "11 mins ago",
    userId: 8,
    like: 74,
    comment: 89,
  },
  {
    id: 9,
    desc: "Is Programming Good?",
    photo: "assets/posts/8.jpg",
    date: "101 mins ago",
    userId: 9,
    like: 3743,
    comment: 8119,
  },
  {
    id: 10,
    desc: "Isaac Ansah will be fine",
    photo: "assets/posts/9.jpg",
    date: "100 mins ago",
    userId: 10,
    like: 3174,
    comment: 8119,
  },
  {
    id: 11,
    desc: "Hatred for none, that is the motto of islam.",
    photo: "assets/posts/10.jpg",
    date: "110 mins ago",
    userId: 11,
    like: 3174,
    comment: 8119,
  },
  {
    id: 12,
    desc: "That is the motto of islam.",
    photo: "assets/posts/11.jpg",
    date: "110 mins ago",
    userId: 12,
    like: 3714,
    comment: 8119,
  },
  {
    id: 13,
    desc: "Who will bet",
    photo: "assets/posts/12.jpg",
    date: "10 mins ago",
    userId: 12,
    like: 34,
    comment: 9,
  },
  {
    id: 14,
    desc: "I need more likes.",
    photo: "assets/posts/13.jpg",
    date: "20 mins ago",
    userId: 14,
    like: 3,
    comment: 8191,
  },
  {
    id: 15,
    desc: "Is the food ready.",
    photo: "assets/posts/14.jpg",
    date: "3 mins ago",
    userId: 15,
    like: 74,
    comment: 819,
  },
  {
    id: 16,
    desc: "What says the time.",
    photo: "assets/posts/15.jpeg",
    date: "10 mins ago",
    userId: 16,
    like: 37,
    comment: 1819,
  },
  {
    id: 17,
    desc: "Wwho will come for weekends.",
    photo: "assets/posts/16.jpeg",
    date: "9 mins ago",
    userId: 17,
    like: 34,
    comment: 819,
  },
  {
    id: 18,
    desc: "A the end.",
    photo: "assets/posts/17.jpg",
    date: "11 mins ago",
    userId: 18,
    like: 374,
    comment: 819,
  },
];
